Repository thabbott/JULES.jl, pull requests merged in 2019-09, with the labels that each got.

#11 Fix Travis badge link
  README.md
Labels: bug

#10 Add RK3 scheme for split-explicit time-stepping
  src/time_steppers.jl
Labels: time stepping

#3 Add notes
  .gitignore
  notes/algorithm.pdf
  notes/algorithm.tex
Labels: documentation

#12 Bootstrap package use PkgTemplates.jl
  .appveyor.yml
  .travis.yml
  Manifest.toml
  Project.toml
  src/JULES.jl
  test/runtests.jl
Labels: package

#14 Add RK3 unit test
  src/JULES.jl
  src/time_steppers.jl
  test/runtests.jl
  test/test_time_steppers.jl
Labels: testing

#19 Disable code coverage submission for Appveyor
  .appveyor.yml
Labels: testing
